### PR TITLE
Sim diagnose

### LINKED ISSUE #572: NaN and Inf values in result of simulate() for truncated_nbinom1 and truncated_nbinom2 family
Hi guys,

a user filed an issue for DHARMa, and after investigating, I found that simulate() produces NaN and inf values in the following example 

```
# run hurdle model for South America
s.america.hurdle <- glmmTMB(final_count ~ species_att_scaled + grassland_scaled +
                         water_scaled + diversity_scaled + elevation_scaled +
                         temp_scaled + precipitation_scaled + age_scaled + area_scaled + 
                         IUCN_scaled + international + pop_scaled + PA_overlap_scaled + 
                         remoteness_scaled + PS_scaled,
                       zi = ~., data = s.america, family = "truncated_poisson")

# explore different families
s.america.hurdle.1 <- update(s.america.hurdle, family = "truncated_nbinom1")
s.america.hurdle.2 <- update(s.america.hurdle, family = "truncated_nbinom2”)
```

See also  https://github.com/florianhartig/DHARMa/issues/152. I assume that this is not intended / expected?

I have the data to reproduce it, but I would have to ask the user to share this. If you can respond here to whom this should be forwarded (if at all), I can forward this to the the user.

Best,
Florian

### PR DESCRIPTION
**Pull request by bbolker**
I think this is ready to go: should fix #572 . Now incorporates Geyer's trunc-poisson and trunc-nbinom code.

### CODE REVIEW

File: glmmTMB/tests/testthat/test-methods.R [hunk 1]
```diff
@@ -398,3 +398,108 @@ test_that("confint works for models with dispformula", {
...
+        m1 <- simfun(y~f, family=f, data=dd, beta=c(-40,39))
+        expect_equal(fixef(m1)$cond, c(`(Intercept)` = -40, f2 = 39))
+        expect_equal(fitted(m1),c(4.24835425529159e-18, 0.367879441171442))
+        ## should NOT get NaN (or zero) for the first group if hack/fix is working
+        expect_equal(unname(unlist(simulate(m1,seed=101))),c(1,1))
+    }
+    
+})
+
+test_that("trunc nbinom sim 2", {
```
Comment (mebrooks) [inline glmmTMB/tests/testthat/test-methods.R:477]: `make test` skips this with the following output
```
test-methods.R:477: skip: trunc nbinom sim 2
Reason: empty test
```
I guess it means it's empty because there's no expectation for `testthat` to check. I don't know if that might cause hangups somewhere in the future.

File: glmmTMB/src/distrib.h [hunk 2]
```diff
@@ -0,0 +1,265 @@
...
+      counter++;
+    }
+    if(ans < 1.) warning("Zeros in simulation of zero-truncated data. Possibly due to low estimated mean.");
+    return ans;
+  }
+
+  /* Simulate from tweedie distribution */
+  template<class Type>
+  Type rtweedie(Type mu, Type phi, Type p) {
+    // Copied from R function tweedie::rtweedie
```
Comment (mebrooks) [inline glmmTMB/src/distrib.h:244]: Maybe we should have added Peter Dunn as a contributor since the Tweedie simulation code was copied from a function he wrote. Should I email him to ask?

File: glmmTMB/src/distrib.h [hunk 3]
```diff
@@ -0,0 +1,265 @@
...
+            if (x > k)
+                return x;
+        }
+    }
+   } // rtruncated_nbinom
+
+  /* Simulate from generalized poisson distribution */
+  template<class Type>
+  Type rgenpois(Type theta, Type lambda) {
+    // Copied from R function HMMpa::rgenpois
```
Comment (mebrooks) [inline glmmTMB/src/distrib.h:122]: Same thing here. Author info for `HMMpa::rgenpois` says "Based on Joe and Zhu (2005). Implementation by Vitali Witowski (2013)." Should one of us email to ask if they prefer a citation and/or contrib credit?

**Review by mebrooks — COMMENTED** [review]
I like that the distrib code is in a separate file to keep things organized. I made some separate comments about code we copied from R functions for `rtweedie` and `rgenpois`.

I guess in a year, we could delete the `rtweedie` code since it's in `TMB` now and a year would give people plenty of time to update `TMB`.

**Comment by mebrooks** [comment]
Good to merge, but some contrib or citations needed for simulation code from R packages.

**Comment by marosteg** [comment]
Is there an expected date for the downloadable update of glmmTMB that will include this fix for #572? Or what would be the best way to utilize this new code in the meantime?

**Comment by mebrooks** [comment]
Technically, it's [downloadable in the master branch on GitHub now](https://github.com/glmmTMB/glmmTMB#from-github-source), but we also plan to release a new version on CRAN as soon as we take care of some other things (#647)
